export const routes = {
  MAIN: "/",
  ALLTOPIC: "/topic",
  COMPONENTS: "components",
  PATH: "props",
  STATE: "state",
  LIFECYCLE: "lifecycle",
  EVENTS: "events",
  KEY: "key",
  REFS: "refs",
  VIRTUALDOM: "virtual-dom",
  LOGIN: "/login",
  POSTS: "/posts",
  ERROR: "/error",
  NOT_FOUND: "/404",
};
