export const routes = {
  MAIN: "/",
  TOPIC: {
    BASE: "/topic",
    COMPONENTS: "components",
    PROPS: "props",
    STATE: "state",
    LIFECYCLE: "lifecycle",
    EVENTS: "events",
    KEY: "key",
    REFS: "refs",
    VIRTUAL_DOM: "virtual-dom",
    FRAGMENT: "fragment",
    REACT_MEMO: "react-memo",
    USEEFFECT: "useEffect",
    USECONTEXT: "useContext",
    USEMEMO: "useMemo",
    REACT_ROUTER: "react-router",
  },
  NOT_FOUND: "*",
};
