import { Routes, Route } from "react-router";
import { WelcomePage } from "./pages/welcomePage/WelcomePage";
import { TopicPage } from "./pages/topicPage/TopicPage";
import "./index.scss";
import { data } from "./data/data";
import { Topic } from "./pages/topicPage/Topic";
function App() {
  return (
    <Routes>
      <Route path="/" element={<WelcomePage />} />
      <Route path="/topic" element={<TopicPage />}>
        <Route
          path="components"
          element={
            <Topic
              title={data[0].title}
              content={data[0].content}
              path={data[0].path}
            />
          }
        />
        <Route
          path="props"
          element={
            <Topic
              title={data[1].title}
              content={data[1].content}
              path={data[1].path}
            />
          }
        />
        <Route
          path="state"
          element={
            <Topic
              title={data[2].title}
              content={data[2].content}
              path={data[2].path}
            />
          }
        />
        <Route
          path="lifecycle"
          element={
            <Topic
              title={data[3].title}
              content={data[3].content}
              path={data[3].path}
            />
          }
        />
        <Route
          path="events"
          element={
            <Topic
              title={data[4].title}
              content={data[4].content}
              path={data[4].path}
            />
          }
        />
        <Route
          path="key"
          element={
            <Topic
              title={data[5].title}
              content={data[5].content}
              path={data[5].path}
            />
          }
        />
        <Route
          path="refs"
          element={
            <Topic
              title={data[6].title}
              content={data[6].content}
              path={data[6].path}
            />
          }
        />
        <Route
          path="virtual-dom"
          element={
            <Topic
              title={data[7].title}
              content={data[7].content}
              path={data[7].path}
            />
          }
        />
        <Route
          path="fragment"
          element={
            <Topic
              title={data[8].title}
              content={data[8].content}
              path={data[8].path}
            />
          }
        />
        <Route
          path="react-memo"
          element={
            <Topic
              title={data[9].title}
              content={data[9].content}
              path={data[9].path}
            />
          }
        />
        <Route
          path="useEffect"
          element={
            <Topic
              title={data[10].title}
              content={data[10].content}
              path={data[10].path}
            />
          }
        />
        <Route
          path="useContext"
          element={
            <Topic
              title={data[11].title}
              content={data[11].content}
              path={data[11].path}
            />
          }
        />
        <Route
          path="useMemo"
          element={
            <Topic
              title={data[12].title}
              content={data[12].content}
              path={data[12].path}
            />
          }
        />
      </Route>
    </Routes>
  );
}

export default App;
